### ISSUE TITLE
为什么文件夹名不用尺寸做为文件夹名

### ISSUE THREAD

**Issue by kaitezhan** [osvlabs/icon-workshop#6]

**Comment by zhanghuanchong** [comment]
@kaitezhan 感谢你的提议，能否详细描述一下你的需求？

**Comment by zhanghuanchong** [comment]
@kaitezhan 

安卓的图标就是以尺寸为文件夹名的：

![image](https://user-images.githubusercontent.com/3062319/79678574-97330b00-822f-11ea-8602-20692aa83123.png)
